version: '3.8'

services:
  # FastAPI backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes:
      - ./app:/work/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Streamlit frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - API_URL=http://backend:8000
    volumes:
      - ./app:/work/app
    restart: unless-stopped
